// source: robo_simul.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.kr.ac.uos.ai.mcmonitor.Changeness', null, global);
goog.exportSymbol('proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment', null, global);
goog.exportSymbol('proto.kr.ac.uos.ai.mcmonitor.EventGenerate', null, global);
goog.exportSymbol('proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment', null, global);
goog.exportSymbol('proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject', null, global);
goog.exportSymbol('proto.kr.ac.uos.ai.mcmonitor.Point', null, global);
goog.exportSymbol('proto.kr.ac.uos.ai.mcmonitor.SimulationCommand', null, global);
goog.exportSymbol('proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.Command', null, global);
goog.exportSymbol('proto.kr.ac.uos.ai.mcmonitor.VirtualObject', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kr.ac.uos.ai.mcmonitor.Point = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kr.ac.uos.ai.mcmonitor.Point, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kr.ac.uos.ai.mcmonitor.Point.displayName = 'proto.kr.ac.uos.ai.mcmonitor.Point';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kr.ac.uos.ai.mcmonitor.Changeness, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kr.ac.uos.ai.mcmonitor.Changeness.displayName = 'proto.kr.ac.uos.ai.mcmonitor.Changeness';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.repeatedFields_, null);
};
goog.inherits(proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.displayName = 'proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kr.ac.uos.ai.mcmonitor.VirtualObject, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kr.ac.uos.ai.mcmonitor.VirtualObject.displayName = 'proto.kr.ac.uos.ai.mcmonitor.VirtualObject';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.repeatedFields_, null);
};
goog.inherits(proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.displayName = 'proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.displayName = 'proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kr.ac.uos.ai.mcmonitor.SimulationCommand = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kr.ac.uos.ai.mcmonitor.SimulationCommand, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.displayName = 'proto.kr.ac.uos.ai.mcmonitor.SimulationCommand';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kr.ac.uos.ai.mcmonitor.EventGenerate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kr.ac.uos.ai.mcmonitor.EventGenerate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kr.ac.uos.ai.mcmonitor.EventGenerate.displayName = 'proto.kr.ac.uos.ai.mcmonitor.EventGenerate';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kr.ac.uos.ai.mcmonitor.Point.prototype.toObject = function(opt_includeInstance) {
  return proto.kr.ac.uos.ai.mcmonitor.Point.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kr.ac.uos.ai.mcmonitor.Point} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.Point.toObject = function(includeInstance, msg) {
  var f, obj = {
    x: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    y: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.Point}
 */
proto.kr.ac.uos.ai.mcmonitor.Point.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kr.ac.uos.ai.mcmonitor.Point;
  return proto.kr.ac.uos.ai.mcmonitor.Point.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.Point} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.Point}
 */
proto.kr.ac.uos.ai.mcmonitor.Point.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setY(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kr.ac.uos.ai.mcmonitor.Point.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kr.ac.uos.ai.mcmonitor.Point.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.Point} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.Point.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
};


/**
 * optional float x = 1;
 * @return {number}
 */
proto.kr.ac.uos.ai.mcmonitor.Point.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.Point} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.Point.prototype.setX = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional float y = 2;
 * @return {number}
 */
proto.kr.ac.uos.ai.mcmonitor.Point.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.Point} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.Point.prototype.setY = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.toObject = function(opt_includeInstance) {
  return proto.kr.ac.uos.ai.mcmonitor.Changeness.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kr.ac.uos.ai.mcmonitor.Changeness} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.toObject = function(includeInstance, msg) {
  var f, obj = {
    objectid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    content: jspb.Message.getFieldWithDefault(msg, 2, ""),
    location: (f = msg.getLocation()) && proto.kr.ac.uos.ai.mcmonitor.Point.toObject(includeInstance, f),
    movement: (f = msg.getMovement()) && proto.kr.ac.uos.ai.mcmonitor.Point.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.Changeness}
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kr.ac.uos.ai.mcmonitor.Changeness;
  return proto.kr.ac.uos.ai.mcmonitor.Changeness.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.Changeness} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.Changeness}
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setObjectid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 3:
      var value = new proto.kr.ac.uos.ai.mcmonitor.Point;
      reader.readMessage(value,proto.kr.ac.uos.ai.mcmonitor.Point.deserializeBinaryFromReader);
      msg.setLocation(value);
      break;
    case 4:
      var value = new proto.kr.ac.uos.ai.mcmonitor.Point;
      reader.readMessage(value,proto.kr.ac.uos.ai.mcmonitor.Point.deserializeBinaryFromReader);
      msg.setMovement(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kr.ac.uos.ai.mcmonitor.Changeness.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.Changeness} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getObjectid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLocation();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.kr.ac.uos.ai.mcmonitor.Point.serializeBinaryToWriter
    );
  }
  f = message.getMovement();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.kr.ac.uos.ai.mcmonitor.Point.serializeBinaryToWriter
    );
  }
};


/**
 * optional string objectID = 1;
 * @return {string}
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.getObjectid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.Changeness} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.setObjectid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string content = 2;
 * @return {string}
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.Changeness} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Point location = 3;
 * @return {?proto.kr.ac.uos.ai.mcmonitor.Point}
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.getLocation = function() {
  return /** @type{?proto.kr.ac.uos.ai.mcmonitor.Point} */ (
    jspb.Message.getWrapperField(this, proto.kr.ac.uos.ai.mcmonitor.Point, 3));
};


/**
 * @param {?proto.kr.ac.uos.ai.mcmonitor.Point|undefined} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.Changeness} returns this
*/
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.setLocation = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.Changeness} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.clearLocation = function() {
  return this.setLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.hasLocation = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Point movement = 4;
 * @return {?proto.kr.ac.uos.ai.mcmonitor.Point}
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.getMovement = function() {
  return /** @type{?proto.kr.ac.uos.ai.mcmonitor.Point} */ (
    jspb.Message.getWrapperField(this, proto.kr.ac.uos.ai.mcmonitor.Point, 4));
};


/**
 * @param {?proto.kr.ac.uos.ai.mcmonitor.Point|undefined} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.Changeness} returns this
*/
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.setMovement = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.Changeness} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.clearMovement = function() {
  return this.setMovement(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kr.ac.uos.ai.mcmonitor.Changeness.prototype.hasMovement = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.prototype.toObject = function(opt_includeInstance) {
  return proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.toObject = function(includeInstance, msg) {
  var f, obj = {
    environmentid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    objectsList: jspb.Message.toObjectList(msg.getObjectsList(),
    proto.kr.ac.uos.ai.mcmonitor.VirtualObject.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment}
 */
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment;
  return proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment}
 */
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEnvironmentid(value);
      break;
    case 2:
      var value = new proto.kr.ac.uos.ai.mcmonitor.VirtualObject;
      reader.readMessage(value,proto.kr.ac.uos.ai.mcmonitor.VirtualObject.deserializeBinaryFromReader);
      msg.addObjects(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvironmentid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getObjectsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.kr.ac.uos.ai.mcmonitor.VirtualObject.serializeBinaryToWriter
    );
  }
};


/**
 * optional string environmentID = 1;
 * @return {string}
 */
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.prototype.getEnvironmentid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.prototype.setEnvironmentid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated VirtualObject objects = 2;
 * @return {!Array<!proto.kr.ac.uos.ai.mcmonitor.VirtualObject>}
 */
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.prototype.getObjectsList = function() {
  return /** @type{!Array<!proto.kr.ac.uos.ai.mcmonitor.VirtualObject>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.kr.ac.uos.ai.mcmonitor.VirtualObject, 2));
};


/**
 * @param {!Array<!proto.kr.ac.uos.ai.mcmonitor.VirtualObject>} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment} returns this
*/
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.prototype.setObjectsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.kr.ac.uos.ai.mcmonitor.VirtualObject=} opt_value
 * @param {number=} opt_index
 * @return {!proto.kr.ac.uos.ai.mcmonitor.VirtualObject}
 */
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.prototype.addObjects = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.kr.ac.uos.ai.mcmonitor.VirtualObject, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.InitializeEnvironment.prototype.clearObjectsList = function() {
  return this.setObjectsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.toObject = function(opt_includeInstance) {
  return proto.kr.ac.uos.ai.mcmonitor.VirtualObject.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kr.ac.uos.ai.mcmonitor.VirtualObject} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.toObject = function(includeInstance, msg) {
  var f, obj = {
    objectid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    position: (f = msg.getPosition()) && proto.kr.ac.uos.ai.mcmonitor.Point.toObject(includeInstance, f),
    type: jspb.Message.getFieldWithDefault(msg, 4, ""),
    propertyMap: (f = msg.getPropertyMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.VirtualObject}
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kr.ac.uos.ai.mcmonitor.VirtualObject;
  return proto.kr.ac.uos.ai.mcmonitor.VirtualObject.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.VirtualObject} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.VirtualObject}
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setObjectid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = new proto.kr.ac.uos.ai.mcmonitor.Point;
      reader.readMessage(value,proto.kr.ac.uos.ai.mcmonitor.Point.deserializeBinaryFromReader);
      msg.setPosition(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 5:
      var value = msg.getPropertyMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kr.ac.uos.ai.mcmonitor.VirtualObject.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.VirtualObject} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getObjectid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPosition();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.kr.ac.uos.ai.mcmonitor.Point.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPropertyMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string objectID = 1;
 * @return {string}
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.getObjectid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.VirtualObject} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.setObjectid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.VirtualObject} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Point position = 3;
 * @return {?proto.kr.ac.uos.ai.mcmonitor.Point}
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.getPosition = function() {
  return /** @type{?proto.kr.ac.uos.ai.mcmonitor.Point} */ (
    jspb.Message.getWrapperField(this, proto.kr.ac.uos.ai.mcmonitor.Point, 3));
};


/**
 * @param {?proto.kr.ac.uos.ai.mcmonitor.Point|undefined} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.VirtualObject} returns this
*/
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.setPosition = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.VirtualObject} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.clearPosition = function() {
  return this.setPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.hasPosition = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string type = 4;
 * @return {string}
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.VirtualObject} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * map<string, string> property = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.getPropertyMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.VirtualObject} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.VirtualObject.prototype.clearPropertyMap = function() {
  this.getPropertyMap().clear();
  return this;};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.prototype.toObject = function(opt_includeInstance) {
  return proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.toObject = function(includeInstance, msg) {
  var f, obj = {
    environmentid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    objectsList: jspb.Message.toObjectList(msg.getObjectsList(),
    proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment}
 */
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment;
  return proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment}
 */
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEnvironmentid(value);
      break;
    case 2:
      var value = new proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject;
      reader.readMessage(value,proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.deserializeBinaryFromReader);
      msg.addObjects(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvironmentid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getObjectsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.serializeBinaryToWriter
    );
  }
};


/**
 * optional string environmentID = 1;
 * @return {string}
 */
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.prototype.getEnvironmentid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.prototype.setEnvironmentid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated ModifiedVirtualObject objects = 2;
 * @return {!Array<!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject>}
 */
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.prototype.getObjectsList = function() {
  return /** @type{!Array<!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject, 2));
};


/**
 * @param {!Array<!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject>} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment} returns this
*/
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.prototype.setObjectsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject=} opt_value
 * @param {number=} opt_index
 * @return {!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject}
 */
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.prototype.addObjects = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.DumpEnvironment.prototype.clearObjectsList = function() {
  return this.setObjectsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.prototype.toObject = function(opt_includeInstance) {
  return proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.toObject = function(includeInstance, msg) {
  var f, obj = {
    objectid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    position: (f = msg.getPosition()) && proto.kr.ac.uos.ai.mcmonitor.Point.toObject(includeInstance, f),
    orientationangle: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject}
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject;
  return proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject}
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setObjectid(value);
      break;
    case 2:
      var value = new proto.kr.ac.uos.ai.mcmonitor.Point;
      reader.readMessage(value,proto.kr.ac.uos.ai.mcmonitor.Point.deserializeBinaryFromReader);
      msg.setPosition(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setOrientationangle(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getObjectid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPosition();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.kr.ac.uos.ai.mcmonitor.Point.serializeBinaryToWriter
    );
  }
  f = message.getOrientationangle();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
};


/**
 * optional string objectID = 1;
 * @return {string}
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.prototype.getObjectid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.prototype.setObjectid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Point position = 2;
 * @return {?proto.kr.ac.uos.ai.mcmonitor.Point}
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.prototype.getPosition = function() {
  return /** @type{?proto.kr.ac.uos.ai.mcmonitor.Point} */ (
    jspb.Message.getWrapperField(this, proto.kr.ac.uos.ai.mcmonitor.Point, 2));
};


/**
 * @param {?proto.kr.ac.uos.ai.mcmonitor.Point|undefined} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject} returns this
*/
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.prototype.setPosition = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.prototype.clearPosition = function() {
  return this.setPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.prototype.hasPosition = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional float orientationAngle = 3;
 * @return {number}
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.prototype.getOrientationangle = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.ModifiedVirtualObject.prototype.setOrientationangle = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.prototype.toObject = function(opt_includeInstance) {
  return proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kr.ac.uos.ai.mcmonitor.SimulationCommand} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.toObject = function(includeInstance, msg) {
  var f, obj = {
    command: jspb.Message.getFieldWithDefault(msg, 1, 0),
    environmentid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.SimulationCommand}
 */
proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kr.ac.uos.ai.mcmonitor.SimulationCommand;
  return proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.SimulationCommand} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.SimulationCommand}
 */
proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.Command} */ (reader.readEnum());
      msg.setCommand(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEnvironmentid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.SimulationCommand} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommand();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getEnvironmentid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.Command = {
  CREATE: 0,
  START: 1,
  RESUME: 2,
  PAUSE: 3,
  STOP: 4,
  DELETE: 5
};

/**
 * optional Command command = 1;
 * @return {!proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.Command}
 */
proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.prototype.getCommand = function() {
  return /** @type {!proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.Command} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.Command} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.SimulationCommand} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.prototype.setCommand = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string environmentID = 2;
 * @return {string}
 */
proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.prototype.getEnvironmentid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.SimulationCommand} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.SimulationCommand.prototype.setEnvironmentid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kr.ac.uos.ai.mcmonitor.EventGenerate.prototype.toObject = function(opt_includeInstance) {
  return proto.kr.ac.uos.ai.mcmonitor.EventGenerate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kr.ac.uos.ai.mcmonitor.EventGenerate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.EventGenerate.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.EventGenerate}
 */
proto.kr.ac.uos.ai.mcmonitor.EventGenerate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kr.ac.uos.ai.mcmonitor.EventGenerate;
  return proto.kr.ac.uos.ai.mcmonitor.EventGenerate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.EventGenerate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kr.ac.uos.ai.mcmonitor.EventGenerate}
 */
proto.kr.ac.uos.ai.mcmonitor.EventGenerate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kr.ac.uos.ai.mcmonitor.EventGenerate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kr.ac.uos.ai.mcmonitor.EventGenerate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kr.ac.uos.ai.mcmonitor.EventGenerate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kr.ac.uos.ai.mcmonitor.EventGenerate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.kr.ac.uos.ai.mcmonitor.EventGenerate.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kr.ac.uos.ai.mcmonitor.EventGenerate} returns this
 */
proto.kr.ac.uos.ai.mcmonitor.EventGenerate.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.kr.ac.uos.ai.mcmonitor);
